//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Sharpnado.Shadows")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyDescription("Add as many custom shadows as you like to any Xamarin.Forms view (Android, iOS, U" +
    "WP). Set Color, Opacity, Blur, and Offset for each shadow.")]
[assembly: System.Reflection.AssemblyProduct("Shadows")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2020")]
[assembly: System.Reflection.AssemblyVersion("1.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1")]


